yarnPath: .yarn/releases/yarn-4.9.1.cjs

nodeLinker: pnp
enableGlobalCache: false

pnpMode: loose

packageExtensions:
  "typescript@*":
    peerDependencies:
      "@nestjs/common": "*"
      "@nestjs/core": "*"
  "@types/express@*":
    peerDependencies:
      "serve-static": "*"
  "@types/express-serve-static-core@*":
    peerDependencies:
      "send": "*"
